[package]
name = "kailua-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
bytemuck.workspace = true
c-kzg.workspace = true
clap.workspace = true
hex.workspace = true
rocksdb.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

alloy = { workspace = true, features = ["full", "kzg"] }
alloy-rpc-types-beacon.workspace = true
op-alloy-protocol.workspace = true

kailua-build.workspace = true
kailua-client.workspace = true
kailua-common.workspace = true
kailua-contracts.workspace = true
kailua-host.workspace = true

kona-host.workspace = true
kona-derive = { workspace = true }

bonsai-sdk.workspace = true
boundless-market.workspace = true
risc0-aggregation.workspace = true
risc0-ethereum-contracts.workspace = true
risc0-zkvm.workspace = true

[dev-dependencies]
assert_cmd = "2.0.16"

[features]
devnet = []
prove = [
    "risc0-zkvm/prove"
]
