name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: risc0/risc0/.github/actions/rustup@main

      - name: Setup mdBook
        run: cargo install mdbook mdbook-mermaid mdbook-admonish

      - name: Build book
        working-directory: ./book
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
